import Foundation

struct CalibrationGuide: Identifiable {
    let id: String
    let title: String
    let purpose: String
    let symptoms: String
    let procedure: [String]
    let measurement: String
    let interpretation: String
    let nextStep: String
    let resultUnit: String?   // unit label for the saved numeric result
}

/// Guided calibration content. Results are saved as CalibrationRecords
/// against printer + material + nozzle + profile.
enum CalibrationLibrary {
    static let guides: [CalibrationGuide] = [
        .init(id: "first-layer", title: "First Layer",
              purpose: "Establish a consistent, well-bonded first layer.",
              symptoms: "Patchy adhesion, ridges, gaps, or transparent over-squished lines.",
              procedure: ["Print a single-layer first-layer test pattern.",
                          "Observe while printing; adjust Z-offset live in 0.02–0.05 mm steps.",
                          "Lines should be fused, uniform, and slightly flattened."],
              measurement: "Visual: continuous lines with no gaps or tearing.",
              interpretation: "Gaps = too high. Torn/transparent = too low. Uniform = correct.",
              nextStep: "Save the final Z-offset; verify with a full-bed pattern.",
              resultUnit: "mm"),
        .init(id: "bed-leveling", title: "Bed Leveling",
              purpose: "Make the nozzle-to-bed distance consistent across the plate.",
              symptoms: "Good adhesion in one area, poor in another.",
              procedure: ["Heat the bed to printing temperature first.",
                          "Run the printer's mesh/manual leveling routine.",
                          "Re-check after any plate change or move."],
              measurement: "First-layer consistency across all corners and center.",
              interpretation: "Uniform first layer everywhere = level.",
              nextStep: "Re-run whenever the printer is moved or the plate swapped.",
              resultUnit: nil),
        .init(id: "z-offset", title: "Z-Offset",
              purpose: "Set the exact nozzle-to-plate gap for the first layer.",
              symptoms: "Poor first layer despite a level bed.",
              procedure: ["Home the printer and start a first-layer test.",
                          "Adjust offset live until lines are slightly squished but not torn."],
              measurement: "Offset value in mm at the best-looking layer.",
              interpretation: "Record the value per plate surface.",
              nextStep: "Save per build plate; plates differ in thickness.",
              resultUnit: "mm"),
        .init(id: "e-steps", title: "E-Steps / Rotation Distance",
              purpose: "Ensure the extruder feeds the commanded amount of filament.",
              symptoms: "Systematic over/under-extrusion across all prints.",
              procedure: ["Mark filament 120 mm above the extruder inlet.",
                          "Command a 100 mm extrusion (hotend hot or filament path disconnected).",
                          "Measure the remaining distance to the mark."],
              measurement: "Actual extruded length = 120 − measured remainder.",
              interpretation: "New value = current × (100 / actual).",
              nextStep: "Update e-steps/rotation distance and repeat to confirm.",
              resultUnit: "steps/mm or mm"),
        .init(id: "extrusion-multiplier", title: "Extrusion Multiplier / Flow Ratio",
              purpose: "Match actual extruded volume to the slicer's expectation.",
              symptoms: "Bulging walls (too high) or gaps between walls (too low).",
              procedure: ["Print a single-wall cube (spiral mode) with flow 1.0.",
                          "Measure wall thickness at several points with calipers.",
                          "New flow = current × (target width / measured width)."],
              measurement: "Average wall thickness vs the sliced line width.",
              interpretation: "Typical results land between 0.94 and 0.98.",
              nextStep: "Save the flow ratio to the filament's slicer profile.",
              resultUnit: "ratio"),
        .init(id: "temp-tower", title: "Temperature Tower",
              purpose: "Find the best nozzle temperature for this filament on this printer.",
              symptoms: "Stringing, weak layers, or dull surfaces.",
              procedure: ["Slice a temperature tower stepping 5 °C per segment.",
                          "Print and label each segment.",
                          "Inspect bridging, overhangs, stringing, and surface per segment."],
              measurement: "Best-looking segment temperature in °C.",
              interpretation: "Choose the lowest temperature with good layer bonding and surface.",
              nextStep: "Update the slicer profile; verify with a strength-critical print if needed.",
              resultUnit: "°C"),
        .init(id: "retraction", title: "Retraction Tuning",
              purpose: "Minimize stringing without causing jams or gaps.",
              symptoms: "Stringing, blobs at seam, or gaps after travel.",
              procedure: ["Print a retraction tower varying distance, then speed.",
                          "Change one variable at a time."],
              measurement: "Lowest distance/speed combination with no stringing.",
              interpretation: "Direct drive typically 0.5–1.5 mm; Bowden 3–7 mm (reference values).",
              nextStep: "Save retraction to the profile; re-check after nozzle changes.",
              resultUnit: "mm"),
        .init(id: "pressure-advance", title: "Pressure / Linear Advance",
              purpose: "Compensate for pressure build-up in the melt zone.",
              symptoms: "Bulging corners, gaps at line starts, inconsistent line width.",
              procedure: ["Print the firmware's PA/LA calibration pattern.",
                          "Select the sharpest corner / most consistent line."],
              measurement: "PA value of the best segment.",
              interpretation: "Direct drive often 0.02–0.06; Bowden higher (reference values).",
              nextStep: "Save to the profile; retune per material and nozzle.",
              resultUnit: "s"),
        .init(id: "max-flow", title: "Maximum Volumetric Speed",
              purpose: "Find the hotend's real volumetric limit for this material.",
              symptoms: "Under-extrusion only at high speeds; clicking extruder.",
              procedure: ["Print a flow-test that steps mm³/s upward.",
                          "Note where extrusion becomes thin or inconsistent."],
              measurement: "Highest mm³/s with consistent extrusion.",
              interpretation: "Set the slicer's volumetric limit ~15% below the observed failure point.",
              nextStep: "Save as a Flow Limit record for printer + hotend + nozzle + material.",
              resultUnit: "mm³/s"),
        .init(id: "bridging", title: "Bridging",
              purpose: "Optimize unsupported spans.",
              symptoms: "Sagging or broken bridges.",
              procedure: ["Print a bridging test at increasing spans.",
                          "Adjust bridge fan, speed, and flow."],
              measurement: "Longest clean span.",
              interpretation: "PLA bridges far better than high-temp materials due to cooling.",
              nextStep: "Save bridge fan/speed to the profile.",
              resultUnit: "mm"),
        .init(id: "overhang", title: "Overhang",
              purpose: "Determine the steepest printable unsupported angle.",
              symptoms: "Curled or rough overhangs.",
              procedure: ["Print an overhang test (30°–80°).",
                          "Inspect surface quality at each angle."],
              measurement: "Steepest angle with acceptable surface.",
              interpretation: "Use the result to decide when supports are needed.",
              nextStep: "Configure support threshold in the slicer accordingly.",
              resultUnit: "°"),
        .init(id: "dimensional", title: "Dimensional Accuracy",
              purpose: "Correct systematic size error per axis.",
              symptoms: "Parts consistently too large or too small.",
              procedure: ["Print a 20–40 mm calibration cube with a marked face.",
                          "Measure X, Y, Z with calipers at mid-height.",
                          "Enter designed vs measured into the Shrinkage tool."],
              measurement: "Per-axis deviation in mm.",
              interpretation: "Uniform small error is usually shrinkage; single-axis error suggests mechanics.",
              nextStep: "Save a scale-compensation profile for this material + printer.",
              resultUnit: "%"),
        .init(id: "hole-tolerance", title: "Hole Tolerance",
              purpose: "Quantify how much holes shrink for this setup.",
              symptoms: "Bolts don't fit modeled holes.",
              procedure: ["Print a hole-gauge test with stepped diameters.",
                          "Test-fit the actual fastener or a gauge pin."],
              measurement: "Smallest hole that fits = measured diameter.",
              interpretation: "Difference between modeled and fitting hole is the compensation.",
              nextStep: "Save to the Hole Compensation tool and Tolerance Library.",
              resultUnit: "mm"),
        .init(id: "xy-compensation", title: "XY Compensation",
              purpose: "Fine-tune horizontal size without rescaling the model.",
              symptoms: "External dimensions slightly off; holes slightly small.",
              procedure: ["Measure external and hole dimensions of a test print.",
                          "Apply half the average error as XY compensation."],
              measurement: "Compensation in mm (positive grows external size).",
              interpretation: "Typical values are ±0.05–0.2 mm.",
              nextStep: "Save per printer + material + nozzle.",
              resultUnit: "mm"),
        .init(id: "cooling", title: "Cooling",
              purpose: "Balance layer bonding against detail and overhangs.",
              symptoms: "Droopy details (too little) or weak layers (too much).",
              procedure: ["Print a fan tower stepping fan speed per segment.",
                          "Evaluate overhangs, bridging, and layer adhesion per segment."],
              measurement: "Best fan percentage for this material.",
              interpretation: "PLA likes 80–100%; ABS/ASA/PC often 0–30% (reference values).",
              nextStep: "Save fan profile per material.",
              resultUnit: "%"),
        .init(id: "input-shaping", title: "Input Shaping Reference",
              purpose: "Reduce ringing by compensating mechanical resonance.",
              symptoms: "Ghosting/ringing after sharp features.",
              procedure: ["Follow your firmware's resonance-test procedure.",
                          "Use an ADXL accelerometer where supported, or print a ringing tower."],
              measurement: "Chosen shaper type and frequency.",
              interpretation: "Higher frequency with less smoothing preserves detail.",
              nextStep: "Record the shaper settings in the printer's notes.",
              resultUnit: "Hz"),
        .init(id: "resonance", title: "Resonance Testing Reference",
              purpose: "Identify mechanical resonance frequencies.",
              symptoms: "Ringing at specific speeds; vibration noise.",
              procedure: ["Run the firmware's resonance measurement, or",
                          "print a VFA/vibration test pattern and inspect banding."],
              measurement: "Resonant frequencies per axis.",
              interpretation: "Peaks indicate where damping or input shaping helps most.",
              nextStep: "Apply input shaping; re-test to confirm improvement.",
              resultUnit: "Hz")
    ]

    static func guide(for id: String) -> CalibrationGuide? {
        guides.first { $0.id == id }
    }
}
